import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context";
import { NoKey } from "@/components/Icons";
import ClientAuth from "@/components/Auth";
import Navbar from "@/components/UI/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`antialiased !bg-white`}>
          <body className="antialiased !bg-white">
            <div className="flex flex-col min-h-screen w-screen">
              <Navbar />
              <main className="flex-1 flex flex-col justify-center items-center px-6">
                {children}
              </main>
            </div>
          </body>
        </body>
      </html>
    </AuthProvider>
  );
}
