import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context";
import { AuthProvider } from "@/context/auth";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get("access_token");
  const isAuth = Boolean(accessToken?.value);
  return (
    <AuthProvider isAuth={isAuth}>
      <AppProvider>
        <html lang="en">
          <body className={`antialiased  h-dvh w-screen flex flex-col`}>
            {children}
          </body>
        </html>
      </AppProvider>
    </AuthProvider>
  );
}
